#!/usr/bin/with-contenv sh

PUID=${PUID:-911}
PGID=${PGID:-911}

if [ ! "$(id -u abc)" -eq "$PUID" ]; then usermod -o -u "$PUID" abc ; fi
if [ ! "$(id -g abc)" -eq "$PGID" ]; then groupmod -o -g "$PGID" abc ; fi

echo "
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

chmod +x /app/rcloneupload.sh
chmod +x /app/supertransfer2.sh
chown -R abc:abc\
    /move \
    /config \
    /json \
    /app 